#!/bin/sh

mod=Super
factor=50
all_tags=$(((1 << 32) - 1))
run=$cfg/scripts/dmenu_run

# for autostart
LOCKFILE=/tmp/river-autostart.lock
terminal="cd $HOME && st"

trackpad="pointer-1267-12423-ELAN1300:00_04F3:3087_Touchpad"
