complete -c elan -n "__fish_use_subcommand" -s v -l verbose -d 'Enable verbose output'
complete -c elan -n "__fish_use_subcommand" -s h -l help -d 'Prints help information'
complete -c elan -n "__fish_use_subcommand" -s V -l version -d 'Prints version information'
complete -c elan -n "__fish_use_subcommand" -f -a "show" -d 'Show the active and installed toolchains'
complete -c elan -n "__fish_use_subcommand" -f -a "install" -d 'Install Lean toolchain'
complete -c elan -n "__fish_use_subcommand" -f -a "uninstall" -d 'Uninstall Lean toolchains'
complete -c elan -n "__fish_use_subcommand" -f -a "default" -d 'Set the default toolchain'
complete -c elan -n "__fish_use_subcommand" -f -a "toolchain" -d 'Modify or query the installed toolchains'
complete -c elan -n "__fish_use_subcommand" -f -a "override" -d 'Modify directory toolchain overrides'
complete -c elan -n "__fish_use_subcommand" -f -a "run" -d 'Run a command with an environment configured for a given toolchain'
complete -c elan -n "__fish_use_subcommand" -f -a "which" -d 'Display which binary will be run for a given command'
complete -c elan -n "__fish_use_subcommand" -f -a "dump-state"
complete -c elan -n "__fish_use_subcommand" -f -a "self" -d 'Modify the elan installation'
complete -c elan -n "__fish_use_subcommand" -f -a "completions" -d 'Generate completion scripts for your shell'
complete -c elan -n "__fish_use_subcommand" -f -a "help" -d 'Prints this message or the help of the given subcommand(s)'
complete -c elan -n "__fish_seen_subcommand_from show" -s h -l help -d 'Prints help information'
complete -c elan -n "__fish_seen_subcommand_from show" -s V -l version -d 'Prints version information'
complete -c elan -n "__fish_seen_subcommand_from install" -s h -l help -d 'Prints help information'
complete -c elan -n "__fish_seen_subcommand_from install" -s V -l version -d 'Prints version information'
complete -c elan -n "__fish_seen_subcommand_from uninstall" -s h -l help -d 'Prints help information'
complete -c elan -n "__fish_seen_subcommand_from uninstall" -s V -l version -d 'Prints version information'
complete -c elan -n "__fish_seen_subcommand_from default" -s h -l help -d 'Prints help information'
complete -c elan -n "__fish_seen_subcommand_from default" -s V -l version -d 'Prints version information'
complete -c elan -n "__fish_seen_subcommand_from toolchain" -s h -l help -d 'Prints help information'
complete -c elan -n "__fish_seen_subcommand_from toolchain" -s V -l version -d 'Prints version information'
complete -c elan -n "__fish_seen_subcommand_from toolchain" -f -a "list" -d 'List installed toolchains'
complete -c elan -n "__fish_seen_subcommand_from toolchain" -f -a "install" -d 'Install a given toolchain'
complete -c elan -n "__fish_seen_subcommand_from toolchain" -f -a "uninstall" -d 'Uninstall a toolchain'
complete -c elan -n "__fish_seen_subcommand_from toolchain" -f -a "link" -d 'Create a custom toolchain by symlinking to a directory'
complete -c elan -n "__fish_seen_subcommand_from toolchain" -f -a "gc" -d 'Garbage-collect toolchains not used by any known project'
complete -c elan -n "__fish_seen_subcommand_from toolchain" -f -a "help" -d 'Prints this message or the help of the given subcommand(s)'
complete -c elan -n "__fish_seen_subcommand_from list" -s h -l help -d 'Prints help information'
complete -c elan -n "__fish_seen_subcommand_from list" -s V -l version -d 'Prints version information'
complete -c elan -n "__fish_seen_subcommand_from install" -s h -l help -d 'Prints help information'
complete -c elan -n "__fish_seen_subcommand_from install" -s V -l version -d 'Prints version information'
complete -c elan -n "__fish_seen_subcommand_from uninstall" -s h -l help -d 'Prints help information'
complete -c elan -n "__fish_seen_subcommand_from uninstall" -s V -l version -d 'Prints version information'
complete -c elan -n "__fish_seen_subcommand_from link" -s h -l help -d 'Prints help information'
complete -c elan -n "__fish_seen_subcommand_from link" -s V -l version -d 'Prints version information'
complete -c elan -n "__fish_seen_subcommand_from gc" -l delete -d 'Delete collected toolchains instead of only reporting them'
complete -c elan -n "__fish_seen_subcommand_from gc" -l json -d 'Format output as JSON'
complete -c elan -n "__fish_seen_subcommand_from gc" -s h -l help -d 'Prints help information'
complete -c elan -n "__fish_seen_subcommand_from gc" -s V -l version -d 'Prints version information'
complete -c elan -n "__fish_seen_subcommand_from help" -s h -l help -d 'Prints help information'
complete -c elan -n "__fish_seen_subcommand_from help" -s V -l version -d 'Prints version information'
complete -c elan -n "__fish_seen_subcommand_from override" -s h -l help -d 'Prints help information'
complete -c elan -n "__fish_seen_subcommand_from override" -s V -l version -d 'Prints version information'
complete -c elan -n "__fish_seen_subcommand_from override" -f -a "list" -d 'List directory toolchain overrides'
complete -c elan -n "__fish_seen_subcommand_from override" -f -a "set" -d 'Set the override toolchain for a directory'
complete -c elan -n "__fish_seen_subcommand_from override" -f -a "unset" -d 'Remove the override toolchain for a directory'
complete -c elan -n "__fish_seen_subcommand_from override" -f -a "help" -d 'Prints this message or the help of the given subcommand(s)'
complete -c elan -n "__fish_seen_subcommand_from list" -s h -l help -d 'Prints help information'
complete -c elan -n "__fish_seen_subcommand_from list" -s V -l version -d 'Prints version information'
complete -c elan -n "__fish_seen_subcommand_from set" -s h -l help -d 'Prints help information'
complete -c elan -n "__fish_seen_subcommand_from set" -s V -l version -d 'Prints version information'
complete -c elan -n "__fish_seen_subcommand_from unset" -l path -d 'Path to the directory'
complete -c elan -n "__fish_seen_subcommand_from unset" -l nonexistent -d 'Remove override toolchain for all nonexistent directories'
complete -c elan -n "__fish_seen_subcommand_from unset" -s h -l help -d 'Prints help information'
complete -c elan -n "__fish_seen_subcommand_from unset" -s V -l version -d 'Prints version information'
complete -c elan -n "__fish_seen_subcommand_from help" -s h -l help -d 'Prints help information'
complete -c elan -n "__fish_seen_subcommand_from help" -s V -l version -d 'Prints version information'
complete -c elan -n "__fish_seen_subcommand_from run" -l install -d 'Install the requested toolchain if needed'
complete -c elan -n "__fish_seen_subcommand_from run" -s h -l help -d 'Prints help information'
complete -c elan -n "__fish_seen_subcommand_from run" -s V -l version -d 'Prints version information'
complete -c elan -n "__fish_seen_subcommand_from which" -s h -l help -d 'Prints help information'
complete -c elan -n "__fish_seen_subcommand_from which" -s V -l version -d 'Prints version information'
complete -c elan -n "__fish_seen_subcommand_from dump-state" -l no-net -d 'Make network operations for resolving channels fail immediately'
complete -c elan -n "__fish_seen_subcommand_from dump-state" -s h -l help -d 'Prints help information'
complete -c elan -n "__fish_seen_subcommand_from dump-state" -s V -l version -d 'Prints version information'
complete -c elan -n "__fish_seen_subcommand_from self" -s h -l help -d 'Prints help information'
complete -c elan -n "__fish_seen_subcommand_from self" -s V -l version -d 'Prints version information'
complete -c elan -n "__fish_seen_subcommand_from self" -f -a "update" -d 'Download and install updates to elan'
complete -c elan -n "__fish_seen_subcommand_from self" -f -a "uninstall" -d 'Uninstall elan.'
complete -c elan -n "__fish_seen_subcommand_from self" -f -a "help" -d 'Prints this message or the help of the given subcommand(s)'
complete -c elan -n "__fish_seen_subcommand_from update" -s h -l help -d 'Prints help information'
complete -c elan -n "__fish_seen_subcommand_from update" -s V -l version -d 'Prints version information'
complete -c elan -n "__fish_seen_subcommand_from uninstall" -s y
complete -c elan -n "__fish_seen_subcommand_from uninstall" -s h -l help -d 'Prints help information'
complete -c elan -n "__fish_seen_subcommand_from uninstall" -s V -l version -d 'Prints version information'
complete -c elan -n "__fish_seen_subcommand_from help" -s h -l help -d 'Prints help information'
complete -c elan -n "__fish_seen_subcommand_from help" -s V -l version -d 'Prints version information'
complete -c elan -n "__fish_seen_subcommand_from completions" -s h -l help -d 'Prints help information'
complete -c elan -n "__fish_seen_subcommand_from completions" -s V -l version -d 'Prints version information'
complete -c elan -n "__fish_seen_subcommand_from help" -s h -l help -d 'Prints help information'
complete -c elan -n "__fish_seen_subcommand_from help" -s V -l version -d 'Prints version information'
