#!/bin/sh

autostart() {
    export XDG_CURRENT_DESKTOP=river
    systemctl --user import-environment WAYLAND_DISPLAY DISPLAY XDG_CURRENT_DESKTOP
    systemctl --user restart xdg-desktop-portal-gtk.service

    swww-daemon &
    mako &
    copyq --start-server &
    waybar &
    kdeconnect-indicator &
    alacritty --daemon
}

if [ ! -e "$LOCKFILE" ]; then
    touch "$LOCKFILE"
    autostart
else
    echo "Autostart skipped, lockfile exists."
fi

