#!/bin/sh

# Set background and border color
riverctl background-color 0x002b36
riverctl border-color-focused 0xe46f22
riverctl border-color-unfocused 0x586e75

# Set keyboard repeat rate
riverctl set-repeat 50 300
