#!/bin/sh

# get pywal colors
. "${HOME}/.cache/wal/colors.sh"

# set background and border color
riverctl background-color 0xe46f22 
riverctl border-color-focused "0x${color10#\#}"
riverctl border-color-unfocused "0x${color0#\#}"

# set keyboard repeat rate
riverctl set-repeat 50 300
