#!/bin/sh

# Scroll by swiping along the edge
riverctl input "$trackpad" scroll-method two-finger

riverctl input "$mouse" accel-profile flat
riverctl input "$mouse" pointer-accel 0.0

riverctl input "$trackpad" tap-button-map left-right-middle
riverctl input "$trackpad" tap enabled
