#!/bin/sh

. "${HOME}/.cache/wal/colors.sh"

riverctl default-layout wideriver

pkill wideriver
wideriver \
    --layout                       left              \
    --layout-alt                   monocle           \
    --stack                        dwindle           \
    --count-master                 1                 \
    --ratio-master                 0.50              \
    --count-wide-left              0                 \
    --ratio-wide                   0.35              \
    --no-smart-gaps                                  \
    --inner-gaps                   10                \
    --outer-gaps                   10                \
    --border-width                 2                 \
    --border-width-monocle         0                 \
    --border-width-smart-gaps      0                 \
    --border-color-focused         "0x${color10#\#}" \
    --border-color-focused-monocle "0x586e75"        \
    --border-color-unfocused       "0x${color0#\#}"  \
    --log-threshold                info              \
   > "/tmp/wideriver.${XDG_VTNR}.${USER}.log" 2>&1 &

# wideriver config
# map is from src/binds
map $mod up    send-layout-cmd wideriver "--layout monocle"
map $mod down  send-layout-cmd wideriver "--layout wide"
map $mod left  send-layout-cmd wideriver "--layout left"
map $mod right send-layout-cmd wideriver "--layout right"

map $mod M     send-layout-cmd wideriver "--layout-toggle"

map $mod L     send-layout-cmd wideriver "--ratio +0.025"
map $mod H     send-layout-cmd wideriver "--ratio -0.025"

map $mod E     send-layout-cmd wideriver "--stack even"
map $mod W     send-layout-cmd wideriver "--stack dwindle"
map $mod I     send-layout-cmd wideriver "--stack diminish"
