#!/bin/sh
exec $(dmenu_path | dmenu -X 11 -Y 10 -W 1898 -h 30 "$@")

# Uncomment for the NAVHISTORY patch (and remove the exec above)
#dmenu_path | dmenu -H "${XDG_CACHE_HOME:-$HOME/.cache/}/dmenu_run.hist" "$@" | ${SHELL:-"/bin/sh"} &
